### PR TITLE
add listTagPackages

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by juhp** [comment]
Thanks for this.
How do you feel about just returning NVR's? But maybe it is cleaner/safer to keep name, ver, rel separate like you are doing?
I suppose it depends on common usage too.

Basically it looks okay to me: I am slightly uncomfortable with calling it `Package`, maybe `KojiPackage` would be better?
Maybe also I should add I am not very happy with my current API, I was lazy to use datatypes heavily,
but moving in that direction would certainly makes such naming choices clearer
(the whole Koji web API seems rather over-complicated and not pretty either, so fleshing out a nicer API is tricky).

**Comment by TristanCacqueray** [comment]
Thank you for the feedback.
NVR sounds good enough since `pkgtreediff` is already decoding it properly. New version renames the type to `KojiPackage`.

**Comment by juhp** [comment]
Thanks

Also just for reference this is how I am using koji-hs currently in fbrnch:
https://github.com/juhp/fbrnch/blob/master/src/Koji.hs
I am still thinking of current koji-hs as a very low-level API, as we gradually use it more we can push common idioms to `Fedora.Koji` (even I found having `BuildID` and `TaskID` exposed outside a bit tedious at times).

I will merge this.
Just one more thing: can we call it `kojiListTaggedBuilds`?
Then probably it makes more sense to rename `KojiPackage` to `KojiBuild` (and similarly `readPackage`)?

**Comment by TristanCacqueray** [comment]
Alright, the new names look much better!

**Comment by juhp** [comment]
Thank you

**Pull request merged**
